name: dim_example
description: this is wechat_flutter demo

version: 0.0.6+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dim:
    path: plugin/wechat_flutter_plugin
  shared_preferences: ^0.5.2+2
  provider: ^3.0.0+1
  cached_network_image: any
  toast: any
  webview_flutter: 0.3.14+1
  image_picker: 0.6.1+2
#  extended_text_field: 0.4.7
  extended_text: ^0.6.6
  url_launcher: any
  connectivity: any
  file: any
  photo_view: ^0.4.2
  dio: ^2.2.2
  open_file: ^2.0.3
  package_info: ^0.4.0+2
  flutter_sound: any
  permission_handler: ^3.1.0
  audioplayers: ^0.13.3
  camera: any
  video_player: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/bsc.webp
    - assets/images/bar_close.png
    - assets/images/tabbar_contacts_c.webp
    - assets/images/tabbar_contacts_s.webp
    - assets/images/tabbar_discover_c.webp
    - assets/images/tabbar_discover_s.webp
    - assets/images/tabbar_chat_c.webp
    - assets/images/tabbar_chat_s.webp
    - assets/images/tabbar_me_c.webp
    - assets/images/tabbar_me_s.webp
    - assets/images/def_avatar.png
    - assets/images/search_black.webp
    - assets/images/search_white.png
    - assets/images/Contact_Female.webp
    - assets/images/Contact_Male.webp
    - assets/images/right_more.png
    - assets/images/favorite.webp
    - assets/images/contacts_add_newmessage.png
    - assets/images/add_addressicon.png
    - assets/images/ic_delete.webp
    - assets/images/ic_right_arrow_black.webp
    - assets/images/ic_right_arrow_grey.webp
    - assets/images/ic_add_friend.webp
    - assets/images/ic_no_data.webp

    - assets/images/login/select_avatar.webp
    - assets/images/login/ic_select_have.webp
    - assets/images/login/ic_select_have_grey.webp
    - assets/images/login/ic_select_no.png

    - assets/images/chat/ic_Emotion.webp
    - assets/images/chat/ic_Keyboard.webp
    - assets/images/chat/ic_details_add.png
    - assets/images/chat/ic_voice.webp
    - assets/images/chat/ic_chat_more.webp
    - assets/images/chat/ic_chat_voice.webp
    - assets/images/chat/ic_details_camera.webp
    - assets/images/chat/ic_details_card.webp
    - assets/images/chat/ic_details_favorite.webp
    - assets/images/chat/ic_details_file.webp
    - assets/images/chat/ic_details_localtion.webp
    - assets/images/chat/ic_details_media.webp
    - assets/images/chat/ic_details_photo.webp
    - assets/images/chat/ic_details_red.webp
    - assets/images/chat/ic_details_transfer.webp
    - assets/images/chat/ic_details_video.webp
    - assets/images/chat/voice_volume_1.webp
    - assets/images/chat/voice_volume_2.webp
    - assets/images/chat/voice_volume_3.webp
    - assets/images/chat/voice_volume_4.webp
    - assets/images/chat/voice_volume_5.webp
    - assets/images/chat/voice_volume_6.webp
    - assets/images/chat/voice_volume_7.webp
    - assets/images/chat/sound_left_0.webp
    - assets/images/chat/sound_left_1.webp
    - assets/images/chat/sound_left_2.webp
    - assets/images/chat/sound_left_3.webp
    - assets/images/chat/sound_right_0.png
    - assets/images/chat/sound_right_1.webp
    - assets/images/chat/sound_right_2.webp
    - assets/images/chat/sound_right_3.png
    - assets/images/chat/icon_sight_close.png
    - assets/images/chat/flip_camera_icon_nor.webp

    - assets/images/mine/ic_small_code.png
    - assets/images/mine/ic_wallet.webp
    - assets/images/mine/ic_card_package.png
    - assets/images/mine/ic_emoji.png
    - assets/images/mine/ic_pay.png
    - assets/images/mine/ic_setting.png

    - assets/images/contact/ic_contacts_details.png
    - assets/images/contact/ic_no_public.webp
    - assets/images/contact/ic_tag.webp
    - assets/images/contact/ic_group.webp
    - assets/images/contact/ic_new_friend.webp
    - assets/images/contact/ic_video.png
    - assets/images/contact/ic_voice.png
    - assets/images/contact/ic_offical.webp
    - assets/images/contact/ic_reda.webp
    - assets/images/contact/ic_scanqr.webp
    - assets/images/contact/ic_search_wework.webp
    - assets/images/contact/ic_contact_add.webp

    - assets/images/discover/ff_Icon_album.webp
    - assets/images/discover/ff_Icon_shake.webp
    - assets/images/discover/ff_Icon_bottle.webp
    - assets/images/discover/ff_Icon_browse.webp
    - assets/images/discover/ff_Icon_nearby.webp
    - assets/images/discover/ff_Icon_qr_code.webp
    - assets/images/discover/ff_Icon_search.webp
    - assets/images/discover/game_center_h5.webp
    - assets/images/discover/mini_program.webp

    - assets/data/friends.json
